---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    traffic.spinnaker.io/load-balancers: '["service spez-service"]'
  labels:
    app: spez
  name: spez-frontend
  namespace: spez-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spez
  template:
    metadata:
      labels:
        app: spez
    spec:
      containers:
        - image: gcr.io/${PROJECT_ID}/spinnaker-spez # will be modified on deployment to point at a digest of an image
          name: spez
