#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    traffic.spinnaker.io/load-balancers: '["service spez-service"]'
  labels:
    app: spez
  name: spez-frontend
  namespace: spez-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spez
  template:
    metadata:
      labels:
        app: spez
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/spinnaker-spez # will be modified on deployment to point at a digest of an image
          name: spez
