---
apiVersion: v1
kind: Service
metadata:
  name: spez-service
  namespace: spez-staging
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    frontedBy: spez-staging # will be applied to backends by Spinnaker
  type: LoadBalancer
  loadBalancerIP: ""
