steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config -f .git/config submodule.spannerclient.url https://github.com/xjdr/spannerclient.git
    git config -f .gitmodules submodule.spannerclient.url https://github.com/xjdr/spannerclient.git
    git submodule init
    git submodule update
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.' ]
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update
    apt-get install -y gettext-base
    mkdir config-all

    # rename config files to be appended with the environment, e.g. staging-service.yaml
    for env in config/prod config/staging; do
      if [ -d $env ]; then
        for file in $env/*; do
          echo "envsubst < $file > config-all/$(basename $env)-$(basename $file)"
          envsubst < $file > config-all/$(basename $env)-$(basename $file)
        done
      fi
    done
artifacts:
  objects:
    location: gs://${_BUCKET_NAME}/${REPO_NAME}-manifests/$SHORT_SHA
    paths: [ 'config-all/*' ]
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
