steps:
- id: 'build spez prod image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.' ]
- id: 'push spez prod image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA' ]
#- id: 'install lpts function'
#  name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - functions
#  - deploy
#  - lastprocessedtimestamp
#  - --quiet
#  - --runtime=go111
#  - --entry-point=LastProcessedTimestamp
#  - --trigger-topic=updates
#  - --service-account=$_SERVICE_ACCOUNT
#  - --source=functions/lastprocessedtimestamp/.
- id: 'deploy spez prod image: tf init'
  name: hashicorp/terraform:0.12.28
  args:
  - init
  - gke-deploy
- id: 'deploy spez prod image: tf plan'
  name: hashicorp/terraform:0.12.28
  args:
  - plan
  - '-var=tailer_image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - '-var=cluster_location=us-central1'
  - '-var=cluster_name=spez'
  - '-out=tf.out'
  - gke-deploy
- id: 'deploy spez prod image: tf apply'
  name: hashicorp/terraform:0.12.28
  args:
  - apply
  - tf.out
- id: 'test force'
  name: 'bash'
  args: [ '-c', 'echo force build again, again, again' ]
#images:
#  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
