steps:
- id: 'build spez prod image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.' ]
#docker tag $IMAGE:$TAG $GCR_REPO/$IMAGE:$TAG
#docker tag $IMAGE:$TAG $GCR_REPO/$IMAGE:latest
#docker push $GCR_REPO/$IMAGE:$TAG
- id: 'push spez prod image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA' ]
#- id: 'install lpts function'
#  name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - functions
#  - deploy
#  - lastprocessedtimestamp
#  - --quiet
#  - --runtime=go111
#  - --entry-point=LastProcessedTimestamp
#  - --trigger-topic=updates
#  - --service-account=$_SERVICE_ACCOUNT
#  - --source=functions/lastprocessedtimestamp/.
- id: 'deploy spez prod image'
  name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
  - --app=$REPO_NAME-ci
  - --version=$SHORT_SHA
  - --cluster=spez
  - --location=us-central1
  - --namespace=default
  - --output=output
  - --annotation=gcb-build-id=$BUILD_ID
- id: 'test'
  name: 'bash'
  args: [ '-c', 'ls -l output' ]
- id: 'test'
  name: 'bash'
  args: [ '-c', 'echo force build' ]
#images:
#  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
