# Copyright (C) 2019 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spanner-tail
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SpannerTail
        version: v1
    spec:
      volumes:
        - name: "service-account"
          secret:
            secretName: "service-account"
      containers:
      - name: spanner-tail
        image: gcr.io/retail-common-services-249016/spez
        imagePullPolicy: Always
        volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
              readOnly: true
              #- name: "certs"
              #mountPath: "/etc/ssl/certs"
        resources:
          limits:
            memory: 16Gi
          requests:
            memory: 8Gi
        ports:
        - containerPort: 9010 #JMX Port
