# This workflow will build a docker image and push it to ghcr.io

name: package and release with docker

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: login to the container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: extract tags, labels for Docker
      id: metadata
      uses: docker/metadata-action@v3.6.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: build and push docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
